config/routes.rb
Yogo::Application.routes.draw do

  namespace :yogo do
    resources :projects do
      resources :collections do
        resources :items
        resources :properties
      end
    end
  end

  

  devise_for :users

  resources :users
  
  root :to => "yogo/projects#index"

end

app/controllers/yogo/base_controller.rb
class Yogo::BaseController < InheritedResources::Base
  respond_to :html, :json, :csv
  
  chainable do
    def parsed_body(format=request.content_type)
      return nil unless format
      format_method = "body_#{format.to_sym}".to_sym
      
      if respond_to?(format_method)
        begin
          send(format_method)
        rescue
          false
        end
      else
        false
      end
    end
    
    protected
    
    def body_json
      JSON.parse(request.body.string)
    end
  end
  
  chainable do
    def build_resource
      if data = parsed_body
        get_resource_ivar || set_resource_ivar(end_of_association_chain.send(method_for_build, data || {}))
      else
        super
      end
    end
    
    def update_resource(object, attributes)
      attributes = attributes || parsed_body
      attributes.delete('id')
      attr_keys = object.attributes.keys.map{|key| key.to_s }
      valid_attributes = attributes.inject({}) {|h,(k,v)| h[k]=v if attr_keys.include?(k); h }
      object.attributes = valid_attributes
      object.save
    end
  end
  
  with_responder do
    include Responders::FlashResponder
    include Responders::HttpCacheResponder
    include ::Yogo::Responders::Json
    include ::Yogo::Responders::Csv
    include ::Yogo::Responders::Pagination
  end
  
  public
  
  # # This should be implemented in controllers for customizing pagination
  # def paginated_scope(relation)
  #   instance_variable_set("@#{controller.controller_name}", relation.paginate(:page => controller.params[:page]))
  # end
  # hide_action :paginated_scope
end

app/controllers/yogo/items_controller.rb
class Yogo::ItemsController < Yogo::BaseController
  defaults :collection_name => 'items',
           :instance_name => 'items'
  
  belongs_to :project, :parent_class => Yogo::Project, :finder => :get, :collection_name => :data_collections
  belongs_to :data_collection, :parent_class => Yogo::Collection::Data, :finder => :get, :param => :collection_id
  
  protected
  
  def collection
    @items ||= end_of_association_chain.all
  end
  
  def resource
    @item ||= collection.get(params[:id])
  end
  
  def build_resource
    if data = parsed_body
      item_data = data['data'] || {}
      get_resource_ivar || set_resource_ivar(end_of_association_chain.send(method_for_build, data || {}))
    else
      super
    end
  end
  
  def update_resource(object, attributes)
    attributes = attributes || parsed_body
    attributes.delete('id')
    attributes = attributes['data'] || {}
    attr_keys = object.attributes.keys.map{|key| key.to_s }
    valid_attributes = attributes.inject({}) {|h,(k,v)| h[k]=v if attr_keys.include?(k); h }
    object.attributes = valid_attributes
    object.save
  end
  
  with_responder do
    def resource_json(item)
      data_collection = controller.send(:parent)
      project = data_collection.project
      
      hash = {}
      hash[:data] = item.as_json
      hash[:uri] = controller.send(:yogo_project_collection_item_path, project, data_collection, item)
      hash[:data_collection] = controller.send(:yogo_project_collection_path, project, data_collection)
      hash
    end
  end
  
  with_responder do
    def csv_header
      data_collection = controller.send(:parent)
      data_collection.schema.map{|s| s.name }.join(',') << "\n"
    end
    
    def collection_csv(resource)
      data_collection = controller.send(:parent)
      result = ''
      resource.each do |item|
        result << data_collection.schema.map{|s| item.send(s.to_s) }.join(',') << "\n"
      end
      result
    end
  end

  private
    
  def method_for_association_build
    :new
  end
  
end

app/controllers/yogo/projects_controller.rb
# Yogo Data Management Toolkit
# Copyright (c) 2010 Montana State University
#
# License -> see license.txt
#
# FILE: projects_controller.rb
# The projects controller provides all the CRUD functionality for the project
# and additionally: upload of CSV files, an example project and rereflection
# of the yogo repository.

class Yogo::ProjectsController < Yogo::BaseController
  defaults :route_collection_name => :projects, :route_instance_name => :project

  # Setting some pagination for this controller
  def paginated_scope(relation)
    instance_variable_set("@projects", relation.paginate(:page => params[:page], :per_page => 1))
  end
  hide_action :paginated_scope

  ##
  # Show all the projects
  #
  # @example 
  #   get /projects
  #
  # @return [Array] Retrives all project and passes them to the view
  #
  # @author Yogo Team
  #
  # @api public
  def index
    super do |format|
      if collection.empty?
        @no_search = true
        @no_menu   = true 
        format.html { render('no_projects') }
      else
        format.html 
      end
    end
  end
  
  protected

  def resource
    @project ||= resource_class.get(params[:id])
  end
  
  def collection
    @projects ||= resource_class.all #.paginate(:page => params[:page], :per_page => 5)
  end
  
  def resource_class
    Yogo::Project
  end
  
  with_responder do
    def resource_json(project)
      hash = super(project)
      hash[:data_collections] = project.data_collections.map do |c| 
        controller.send(:yogo_project_collection_path, project, c)
      end
      hash
    end
  end
  
end

app/views/yogo/projects/_form.html.haml
#project-new
  = f.text_field(:name, :label => "Project Name:" )
  = f.text_area(:description, :label => "Project Description: ")

app/views/yogo/projects/edit.html.haml
#content-settings-main
  .small.boxed
    %h1#content-title
      = @project.name
      #subtitle Project Settings
  .small.boxed
    .rbox.tight
      = link_to("Delete", yogo_project_path(@project), :method => :delete, :class => 'delete-link', 
                :confirm => "Do you want to delete the #{@project.name} project?\nThere is no undo! Continue?" )
      - form_for(:project, @project, :url => yogo_project_path(@project), :builder => YogoFormBuilder, :html => {:method => :put}) do |f|
        = f.check_box(:is_private, :label => image_tag('icons/private_16.png') + " Private")
        = f.text_field(:name)
        = f.text_area(:description, :label => "Description: ")
        %h5.tight  Members
        .rbox.tight
          %table
            %thead
              %th User
              %th Roles
              %th
            %tbody
              - unless @project.roles.empty? 
                - @project.users.each do |user|
                  %tr
                    %td= user.name
                    %td= @project.roles.select{|role| role.users.include?(user) }.map{|role| role.name }.join(', ')     
                    %td 
                      #operation-links
                        #edit-link
                          = link_to("Edit", edit_yogo_project_membership_path(@project, user), :class => 'edit-link')
                        #delete-link
                          = link_to("Delete", yogo_project_membership_path(@project, user), :method => :delete, 
                                    :class => 'delete-link',
                                    :confirm => "Do you want to remove #{user.name} from the #{@project.name} project?")
        
        .form-element
          = f.submit('Update', :class => 'update-link')
          = link_to('Cancel', yogo_projects_path, :class => 'cancel-link')

  / - if User.count > @project.users.count
  /     #content-settings-extra
  /       .rbox.tight
  /         - form_for(:membership, :url => yogo_project_memberships_path(@project)) do |f|
  /           - field_set_tag("Users:") do
  /             - for user in User.all do
  /               - unless @project.users.include?(user)
  /                 = check_box_tag("memberships[users][]", user.id, false, :class => "memberships_users_#{user.id}", :id => "memberships_users_#{user.id}")
  /                 = label_tag("memberships_users_#{user.id}", user.name) 
  /           - field_set_tag("Role:") do
  /             - for role in Role.all do
  /               = check_box_tag("memberships[roles][]", role.id, false, :class => "memberships_#{role.id}", :id => "memberships_#{role.id}")
  /               = label_tag("memberships_#{role.id}", role.name)
  /           = f.submit('Update', :class => 'update-link')
  /           = link_to('Cancel', yogo_projects_path, :class => 'cancel-link')
  

app/views/yogo/projects/index.html.haml
%h1#content-title Dashboard
#content-actions
  .content-action-links
    = link_to("Create a Project", new_yogo_project_path, :class => 'medium-button-link')
    / - unless Yogo::Setting[:example_project_loaded]
    /     = link_to("Load Example Project", loadexample_yogo_projects_path, 
    /       :class => 'medium-button-link', :method => :post)
  .content-pagination-links= will_paginate(collection)

#content-block
  - for project in collection
    .content-row-block
      /.project-icon= link_to(image_tag('mock-project-icon.jpg'), project_path(project) )

      .project-text
        %h2
          = link_to(project.name, yogo_project_path(project) ) 
          = image_tag('icons/private_16.png', :title => 'Private Project') if project.is_private?
        .action-links
          = link_to("Project Settings", edit_yogo_project_path(project), :class => 'button-link')
        %p.rbox.tight
          - if project.description && project.description.length > 0
            %strong= link_to('Project Description', edit_yogo_project_path(project), :title => 'Edit Project Description')
            %br/
            %em= tooltip(project.description, 
                    project.name + ' Description', 200)
          - else
            %em= link_to('[Add Project Description]', edit_yogo_project_path(project))
          
      .project-datasets
        - if project.data_collections.empty?
          %p 
            There are no datasets associated with this project.<br />
            = link_to("Add Collections", '#', :class => 'button-link')
        - else
          %table
            %thead
              %tr
                %th Dataset
                %th New
                %th Total
            %tbody
              - for dataset in project.data_collections
                %tr
                  %td= link_to dataset.public_name,
                        project_yogo_data_index_path(project, dataset) 
                  %td= link_to(dataset.count(:created_at.gt => 1.week.ago),
                        project_yogo_data_index_path(project, dataset))
                  %td= link_to(dataset.count, project_yogo_data_index_path(project, dataset))
                  /%td= link_to(image_tag('table_edit.png', :title => "Browse Data") + " Browse",
                  /      project_yogo_data_index_path(project, dataset))
                  / TODO: Show the model editor
                  /%td= link_to(image_tag('layout_edit.png', 
                  /      :title => "Describe Dataset") + " Describe",
                  /      project_yogo_models_path(project))
                  /%td= link_to(image_tag('table_add.png', 
                  /      :title => "Import Spreadsheet") + " Import", 
                  /      import_csv_path(project))

#pagination-links= will_paginate(collection) 

app/views/yogo/projects/new.html.haml
.small-centered
  .rbox.dashed
    = form_for(@project, :as => :project, :url => yogo_projects_path, :builder => YogoFormBuilder) do |form|
      = render :partial => 'yogo/projects/form', :locals => {:f => form}
      .form-element
        =form.submit('Save and Continue', :class => 'button-link')
        = link_to('Cancel', root_path, :class => 'cancel')

app/views/yogo/projects/no_projects.html.haml
.description-column
  #intuitive.tight.rbox
    %h3 Intuitive
    %p The Yogo Toolkit was designed and tested with scientists in mind, not database administrators. The user interface and workflow is simple and straightforward. 

  #powerful.tight.rbox
    %h3 Powerful
    %p With the help of Yogo's specially designed dataset editor, you can describe your data and begin from scratch in minutes. Or, if you choose, you can start off by importing data from a spreadsheet file to create your database.

  #flexible.tight.rbox
    %h3 Flexible
    %p Unlike the majority of data management tools, Yogo makes it effortless to revise and develop your database as you go. You can make changes at any time without worrying that your data will be lost.

.title-column
  %h1.text-center Welcome to the<br />Yogo Data Management Toolkit
  .text-center
    = link_to("Create a Project", new_yogo_project_path, :class => 'big-button-link') 

  / #getting-started
  /    .happy.rbox
  /      %h3 Try It Out
  /      %p Try out the sysetem with the example project, #{link_to('load the Example Project', loadexample_yogo_projects_path, :method => :post)} and you can browse an example project of the data collected by Dr. Gwen Jacobs of the cricket cercal system.
  /      .text-center
  /        = link_to("Load Example Project", loadexample_yogo_projects_path, :class => 'medium-button-link', :method => :post)

app/views/yogo/projects/show.html.haml
%h1#content-title
  #subtitle
    Yogo Project
  = resource.name
  = image_tag('icons/private_32.png', :title => 'Private Project') if resource.is_private

#content-actions
  .content-action-links
    = link_to("Project Settings", edit_yogo_project_path(resource), :class => 'medium-button-link')
    = link_to("Delete Project", yogo_project_path(resource), 
     :method => :delete, :class => 'medium-button-link', 
     :confirm => "There is no undo.\n Continue?" )
    /= link_to("Import Spreadsheet", import_csv_path(resource), :class => 'button-link')
    /- if !current_user.nil? && current_user.has_permission?(:edit_project, resource)
    /  = link_to("Manage Users", project_users_path(resource), :class => 'button-link')

//= render(:partial => 'layouts/sidebar') %>

#content-block
  - for dataset in resource.data_collections
    - @item = dataset.new
    .content-row-block
      .dataset-name
        %h2= link_to dataset.public_name, project_yogo_data_index_path(resource, dataset)
        .vertical-links
          .link= link_to("Add a new #{dataset.public_name}", new_project_yogo_data_path(resource, dataset), 
                :class => 'button-link')
          .link= link_to("Browse All Data", project_yogo_data_index_path(resource, dataset), 
                  :class => 'button-link')
          .link= link_to("Import Spreadsheet", import_csv_path(resource), :class => 'button-link')
          .link= link_to("Export Spreadsheet", project_yogo_data_index_path(resource, dataset, 
                  :format => 'csv'), :class => 'button-link')
      .dataset-info
        .action-tabs
          %ul
            %li <a href="##{dataset.to_param}-dataset-details">Dataset Details</a>
            %li <a href="##{dataset.to_param}-query">Query</a>
            %li <a href="##{dataset.to_param}-quickview">Quickview</a>
          = render(:partial => 'yogo/models/dataset',       :locals => {:dataset => dataset})
          = render(:partial => 'yogo/projects/build_query', :locals => {:dataset => dataset})
          = render(:partial => 'yogo/data/quickview',       :locals => {:dataset => dataset})